services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  griiv.prestashop.module.contracts.module:
    class: Module
    factory: [ 'Module', 'getInstanceByName' ]
    arguments:
      - 'gauthenticate'

  griiv.prestashop.module.contracts.context:
    class: Context
    factory: [ 'Context', 'getContext' ]

  Griiv\Prestashop\Module\Contracts\Hook:
    class: Griiv\Prestashop\Module\Contracts\Hook
    public: false
    arguments:
      - '@griiv.prestashop.module.contracts.module'
      - '@griiv.prestashop.module.contracts.context'